version: '3'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_DC=datacenter1
    volumes:
      - ./cassandra-data:/var/lib/cassandra
